// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ0WWy2rgvUU0v7jB1Vf2vj5pI8wpXiS8',
    appId: '1:773680205511:web:a9f51d888f75ea0681b8e2',
    messagingSenderId: '773680205511',
    projectId: 'abashopdb',
    authDomain: 'abashopdb.firebaseapp.com',
    storageBucket: 'abashopdb.appspot.com',
    measurementId: 'G-L8E1E8THM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYg1-isIJTSK1lE6IzbVKQrxRJHyP6-Xo',
    appId: '1:773680205511:android:b29717e2489820dc81b8e2',
    messagingSenderId: '773680205511',
    projectId: 'abashopdb',
    storageBucket: 'abashopdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDarFEVd8Dz1PX0bLsBIa3XXHmGgH0F2vI',
    appId: '1:773680205511:ios:1e33c2cad77cd6c481b8e2',
    messagingSenderId: '773680205511',
    projectId: 'abashopdb',
    storageBucket: 'abashopdb.appspot.com',
    iosBundleId: 'com.firebase.abashop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDarFEVd8Dz1PX0bLsBIa3XXHmGgH0F2vI',
    appId: '1:773680205511:ios:bc75ac4b155e1b0481b8e2',
    messagingSenderId: '773680205511',
    projectId: 'abashopdb',
    storageBucket: 'abashopdb.appspot.com',
    iosBundleId: 'com.firebase.abashop.RunnerTests',
  );
}
